apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
  labels:
    app: phpapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpapp
  template:
    metadata:
      labels:
        app: phpapp
    spec:
      containers:
        - name: phpapp
          image: greglebreton/phpapp:1.0
          # resources:
          #   requests:
          #     memory: "250Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "500Mi"
          #     cpu: "750m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: registryhub