apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
        - name: aspnetapp
          image: greglebreton/aspnetapp:1.0
          # resources:
          #   requests:
          #     memory: "250Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "500Mi"
          #     cpu: "750m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: registryhub