apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phpapp
  name: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: phpapp
  type: NodePort
status:
  loadBalancer: {}
