Vagrant.configure("2") do |config|

  # Linux OS CentOS
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.linked_clone = true
  end

  # Application server
  config.vm.define "master" do |mas|
    mas.vm.hostname = "master"
    # static ip address
    mas.vm.network :private_network, ip: "192.168.60.5"
  end
  config.vm.define "noeud" do |noeud|
    noeud.vm.hostname = "noeud"
    # static ip address
    noeud.vm.network :private_network, ip: "192.168.60.6"
  end  


end
